name: forveel
description: A new Flutter project.

version: 1.27.19+24

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.4.0
  page_transition: ^2.0.9
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.1.0
  vibration: ^1.2.3
  image_picker: ^0.8.7+3
  connectivity: ^3.0.6
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.5
  path_provider: ^2.0.14
  url_launcher: ^6.0.5
  cached_network_image: ^3.2.3
  toast: ^0.3.0
  location: ^4.4.0
  firebase_auth: ^4.4.1
  qr_flutter: ^4.0.0
  cloud_firestore: ^4.5.1
  google_fonts: ^4.0.3
  simple_animations: ^5.0.0+3
  geocoder: ^0.2.1
  time_formatter: ^1.0.0
  firebase_messaging: ^14.4.0
  photo_view: ^0.14.0
  snaplist: ^0.1.8
  # flutter_advanced_networkimage: ^0.7.0
  fluttertoast: ^8.0.7
  flutter_svg: ^2.0.5
  geocoder2: ^1.4.0
  get: ^4.6.5
  walletconnect_flutter_v2: ^2.0.0
  walletconnect_dart: ^0.0.11
  web3dart: 2.6.1
  provider: ^6.0.0
  flutter_web3: ^2.1.9
  http: ^0.13.3
  permission_handler: ^10.0.0
  notification_permissions: ^0.6.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.0

  flutter_lints: ^2.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/car.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/forveel_logo.jpg
    - assets/images/emoji.png
    - assets/images/emojia.png
    - assets/images/emojib.png
    - assets/images/forveel_logo_png.png
    - assets/images/mechanic.png
    - assets/images/sad.png
    - assets/images/smile.png
    - assets/images/worker.png
    - assets/images/pizza.png
    - assets/abi/servicerequest.abi.json