// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvnI_HT5yu35fnpHSc_Gr6z24QDKpajaA',
    appId: '1:945002006532:android:43a7c0e780e30aca4b8d51',
    messagingSenderId: '945002006532',
    projectId: 'mechanicfinder-506f4',
    storageBucket: 'mechanicfinder-506f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhf_t8jV_gedw7iTA-6T-EwdeCkabsq0s',
    appId: '1:945002006532:ios:f8a4094fa8291f944b8d51',
    messagingSenderId: '945002006532',
    projectId: 'mechanicfinder-506f4',
    storageBucket: 'mechanicfinder-506f4.appspot.com',
    androidClientId: '945002006532-hh15nn1n1kh49h7regb20dmjkgf2q6ao.apps.googleusercontent.com',
    iosClientId: '945002006532-amasj0lqp5vdep7oie5vop0pdk9hhh99.apps.googleusercontent.com',
    iosBundleId: 'com.example.mechanicfinder',
  );
}
